

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - PORT=8000
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - SECRET_KEY=your-secret-key-for-local-development
      - DATABASE_URL=sqlite:///db.sqlite3
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/media:/app/media
      - ./backend/temp_downloads:/app/temp_downloads
      - ./backend/uploaded_files:/app/uploaded_files
      - ./backend/logs:/app/logs
    networks:
      - excel-mapper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.local
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - excel-mapper-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  excel-mapper-network:
    driver: bridge