"""Which row of an uploaded sheet is the header, and what columns it declares.

A port of the detection that has only ever existed in the browser
(`frontend/src/pages/UploadFiles.js`). Until now the file was opened client-side,
scored there, and the answer posted to the server as `headerRow` — so anything
that is not a browser had to guess row 1, which is wrong for most real BOMs.
They open with a title block, a report date, a blank line or two, and the table
starts several rows down.

Everything here is pure: it takes rows (a list of lists, as read positionally
from the file) and returns numbers and names. Reading the file stays with the
caller, which already knows how to handle csv encodings and Excel sheets.

Kept deliberately faithful to the JS — the same keyword list, the same weights,
the same special cases — because the two have to agree about a file. A user and
an agent disagreeing about where the table starts is worse than either one being
slightly wrong.
"""

import re

# How far down to look for a header. Beyond this a sheet is preamble, not a table.
HEADER_SCAN_ROWS = 40

HEADER_KEYWORDS = [
    re.compile(pattern) for pattern in (
        r'\boperation\b', r'\bsequence\b', r'\bcomponent\b', r'\bitem\b', r'\bpart\b',
        r'\bdescription\b', r'\btype\b', r'\buom\b', r'\bqty\b', r'\bqnty\b', r'\bquantity\b',
        r'\bmanufacturer\b', r'\bmanufacture\b', r'\bmpn\b', r'\bmfr\b', r'\bdesignator',
        r'\breference\b', r'\bvendor\b', r'\bsupplier\b', r'\bmfg\b',
        r'\brelease\b', r'\bstatus\b', r'\brevision\b', r'\bclassification\b',
    )
]

# Report furniture. A row that says "Report date" is a caption, not a header.
METADATA_PATTERNS = [
    re.compile(pattern) for pattern in (
        r'part list for', r'report date', r'^description:?$', r'^required\b', r'^optional\b',
        r'generated by', r'printed on', r'page \d+', r'^plm$', r'^bom report$',
    )
]

_NON_ALNUM = re.compile(r'[^a-z0-9]+')
_STRIP_SYMBOLS = re.compile(r'[^A-Za-z0-9]')
_LONG_DIGITS = re.compile(r'^\d{5,}$')
_SENTENCE_END = re.compile(r'[.!?](\s|$)')
_HAS_ALNUM = re.compile(r'[A-Za-z0-9]')
_TWO_CAPS = re.compile(r'[A-Z]{2}')
_MFG_BLOCK = re.compile(r'manufacturer part number|part numbers|manufacturers', re.IGNORECASE)


def normalize_row_cells(row):
    """Every cell as trimmed text, so blanks and numbers compare the same way."""
    cells = []
    for cell in (row or []):
        cells.append('' if cell is None else str(cell).strip())
    return cells


def normalize_header_key(value):
    """A label reduced to words: 'Ref. Designator' and 'ref designator' match."""
    return _NON_ALNUM.sub(' ', str(value or '').lower()).strip()


def is_numeric_like(value):
    """True for anything that reads as a number once separators are removed."""
    text = str(value or '').replace(',', '').strip()
    if text == '':
        return False
    try:
        float(text)
        return True
    except ValueError:
        return False


def find_multi_level_mfg_parts_header_row(rows):
    """The header row of a multi-level sheet that lists manufacturer parts in blocks.

    This shape scores badly on the general rules — its leading columns are blank,
    because the level is carried by indentation — so it is recognised outright
    rather than left to the scorer. Returns a 1-based row number, or 0.
    """
    normalized_rows = [normalize_row_cells(row) for row in (rows or [])]
    for row_index in range(min(len(normalized_rows), HEADER_SCAN_ROWS)):
        row = normalized_rows[row_index]
        keys = [normalize_header_key(cell) for cell in row]
        description_index = next((i for i, key in enumerate(keys) if key == 'description'), -1)
        has_quantity = any(key in ('qty', 'quantity', 'qnty') for key in keys)
        has_mfg_parts = any(
            key in ('mfg parts', 'mfg part', 'manufacturer parts', 'manufacturer part')
            for key in keys
        )
        if description_index <= 0 or not has_quantity or not has_mfg_parts:
            continue

        # The columns to the left of Description hold the level, and they are
        # unlabelled — that is what makes this shape distinctive.
        if any(row[:description_index]):
            continue

        below = normalized_rows[row_index + 1:row_index + 25]
        item_rows = [
            next_row for next_row in below
            if any(_HAS_ALNUM.search(cell) for cell in next_row[:description_index])
            and description_index < len(next_row) and next_row[description_index]
        ]
        mfg_block_rows = [
            next_row for next_row in below
            if any(_MFG_BLOCK.search(cell) for cell in next_row)
        ]
        if len(item_rows) >= 3 and mfg_block_rows:
            return row_index + 1
    return 0


def has_single_usable_column(rows):
    """True when everything landed in one column.

    A CSV saved with the wrong delimiter parses this way. Every row then looks
    alike, so the scorer's "best" row is noise and row 1 is the honest answer.
    """
    populated = set()
    for row in (rows or []):
        for index, cell in enumerate(normalize_row_cells(row)):
            if cell != '':
                populated.add(index)
    return len(populated) <= 1


def score_header_row(rows, row_index):
    """How much this row looks like column labels rather than data or prose.

    The weights are the browser's, unchanged. They balance three things: a header
    is wide and made of short distinct labels; it often uses known BOM words; and
    it has data underneath it. Long sentences, numbers, and long identifiers all
    count against — those are rows of data, or the report's own caption.
    """
    row = rows[row_index] if row_index < len(rows) else []
    cells = normalize_row_cells(row)
    filled = [cell for cell in cells if cell != '']
    if not filled:
        return float('-inf')

    count = len(filled)
    avg_length = sum(len(cell) for cell in filled) / count
    long_cells = sum(1 for cell in filled if len(cell) > 60)
    prose_cells = sum(
        1 for cell in filled
        if _SENTENCE_END.search(cell) or len(cell.split()) > 8
    )
    numeric_cells = sum(1 for cell in filled if is_numeric_like(cell))
    normalized = [normalize_header_key(cell) for cell in filled]
    keyword_hits = sum(
        1 for cell in normalized if any(pattern.search(cell) for pattern in HEADER_KEYWORDS)
    )
    metadata_hits = sum(
        1 for cell in normalized if any(pattern.search(cell) for pattern in METADATA_PATTERNS)
    )
    compact_filled = [_STRIP_SYMBOLS.sub('', cell) for cell in filled]
    long_numeric_identifiers = sum(1 for cell in compact_filled if _LONG_DIGITS.match(cell))

    data_row_signals = 0
    for cell_index, cell in enumerate(filled):
        compact = compact_filled[cell_index] if cell_index < len(compact_filled) else ''
        key = normalized[cell_index] if cell_index < len(normalized) else ''
        if _LONG_DIGITS.match(compact):
            data_row_signals += 1
            continue
        if is_numeric_like(cell) and count >= 4:
            try:
                if float(str(cell).replace(',', '')) <= 999:
                    data_row_signals += 1
                    continue
            except ValueError:
                pass
        if len(cell) > 12 and re.search(r'\s', cell) and not any(
            pattern.search(key) for pattern in HEADER_KEYWORDS
        ):
            data_row_signals += 1

    header_keyword_ratio = keyword_hits / count
    unique_ratio = len(set(normalized)) / count
    indexes = [index for index, cell in enumerate(cells) if cell]
    next_rows = [normalize_row_cells(r) for r in rows[row_index + 1:row_index + 9]]
    supported_columns = sum(
        1 for index in indexes
        if any(index < len(next_row) and next_row[index] for next_row in next_rows)
    )
    data_rows_below = sum(
        1 for next_row in next_rows
        if any(index < len(next_row) and next_row[index] for index in indexes)
    )
    mostly_upper = sum(
        1 for cell in filled
        if re.search(r'[A-Z]', cell) and cell == cell.upper() and _TWO_CAPS.search(cell)
    )
    short_label_ratio = sum(
        1 for cell in filled if len(cell) <= 35 and len(cell.split()) <= 5
    ) / count
    support_ratio = supported_columns / count if count else 0
    # Numbers in a row that has data under it are far less damning: a header of
    # years or sizes is real. With nothing underneath, numbers mean data.
    numeric_penalty = 6 if support_ratio >= 0.5 else 25

    return (
        count * 2.4                       # wide rows are more likely to be the header
        + keyword_hits * 8                # known BOM/table labels are strong signals
        + (18 if keyword_hits >= 3 else 0)
        + header_keyword_ratio * 14
        + supported_columns * 1.4         # real headers usually have data underneath
        + data_rows_below * 1.2
        + short_label_ratio * 8
        + mostly_upper * 0.7
        - (long_cells / count) * 40       # help text is long
        - (prose_cells / count) * 30      # help text reads like sentences
        - (numeric_cells / count) * numeric_penalty
        - long_numeric_identifiers * 18   # item-code rows are data, not headers
        - max(0, data_row_signals - keyword_hits) * 6
        - metadata_hits * 18              # report titles/date rows are not headers
        - (20 if count <= 2 else 0)
        - max(0, avg_length - 30) * 0.6
        + unique_ratio * 10               # column labels are mostly distinct
    )


def detect_header_row(rows):
    """The 1-based row number that holds the column labels."""
    scan = (rows or [])[:HEADER_SCAN_ROWS]
    multi_level = find_multi_level_mfg_parts_header_row(scan)
    if multi_level:
        return multi_level
    if has_single_usable_column(scan):
        return 1

    best_row = 0
    best_score = float('-inf')
    for index in range(len(scan)):
        score = score_header_row(scan, index)
        if score > best_score:
            best_score = score
            best_row = index
    return best_row + 1


def usable_column_descriptors(rows, header_index):
    """The columns a sheet actually declares, named and de-duplicated.

    Keeps every named column even if it looks generic or is currently empty, and
    keeps unnamed columns that hold data (they get `Column N`). Only a column
    with neither a name nor a value is dropped — that is padding, not data.
    """
    all_rows = rows or []
    header_row = normalize_row_cells(
        all_rows[max(0, header_index)] if max(0, header_index) < len(all_rows) else []
    )
    data_rows = [normalize_row_cells(row) for row in all_rows[header_index + 1:]]
    max_length = max(
        [len(header_row)] + [len(row) for row in data_rows] + [0]
    )

    used = {}
    descriptors = []
    for index in range(max_length):
        raw_header = header_row[index] if index < len(header_row) else ''
        has_header = raw_header != ''
        has_data = any(index < len(row) and row[index] for row in data_rows)
        if not has_header and not has_data:
            continue
        base = raw_header or ('Column %d' % (index + 1))
        seen = used.get(base, 0)
        used[base] = seen + 1
        descriptors.append({
            'index': index,
            'header': base if seen == 0 else '%s %d' % (base, seen + 1),
            'is_generated': not raw_header,
        })
    return descriptors


def headers_at_row(rows, header_row):
    """Just the column names, for a 1-based header row."""
    header_index = max(0, int(header_row or 1) - 1)
    return [column['header'] for column in usable_column_descriptors(rows, header_index)]


def describe_sheet(rows, header_row=None):
    """What the caller needs to show or decide: the header row and its columns.

    `header_row` overrides detection — that is the "user changed it" path — and
    is clamped so a bad value cannot produce an empty sheet.
    """
    all_rows = rows or []
    detected = detect_header_row(all_rows)
    if header_row is None:
        chosen = detected
    else:
        try:
            chosen = int(header_row)
        except (TypeError, ValueError):
            chosen = detected
    chosen = max(1, min(chosen, len(all_rows) or 1))
    return {
        'header_row': chosen,
        'detected_header_row': detected,
        'headers': headers_at_row(all_rows, chosen),
        'total_rows': len(all_rows),
    }
