# Generated by Django 5.2.1 on 2025-08-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0002_add_formula_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('formula_rules', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'excel_mapper_tag_template',
                'ordering': ['-created_at'],
            },
        ),
    ]
