# Generated by Django 5.2.1 on 2025-08-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0004_add_factwise_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='default_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
