# Generated by Django 5.2.1 on 2025-08-07 06:30

from django.db import migrations

def create_default_templates(apps, schema_editor):
    """
    Creates default mapping and tag templates for the application.
    """
    MappingTemplate = apps.get_model('excel_mapper', 'MappingTemplate')
    TagTemplate = apps.get_model('excel_mapper', 'TagTemplate')
    db_alias = schema_editor.connection.alias

    print("\n[Data Migration] Creating default templates...")

    # Create a general-purpose mapping template
    print(" - Creating 'General Purpose BOM Template'...")
    try:
        MappingTemplate.objects.using(db_alias).update_or_create(
            name="General Purpose BOM Template",
            defaults={
                "description": "A standard template for general bill of materials.",
                "template_headers": ["Part Number", "Description", "Quantity", "Manufacturer"],
                "source_headers": ["Part Number", "Description", "Quantity", "Manufacturer"],
                "mappings": {
                    "Part Number": "Part Number",
                    "Description": "Description",
                    "Quantity": "Quantity",
                    "Manufacturer": "Manufacturer"
                },
                "session_id": "default_template",
                "formula_rules": [],
                "factwise_rules": [],
                "default_values": {}
            }
        )
        print("   ...OK")
    except Exception as e:
        print(f"   ...FAILED: {e}")


    # Create a default tag template for capacitors
    print(" - Creating 'Capacitor Tags' template...")
    try:
        TagTemplate.objects.using(db_alias).update_or_create(
            name="Capacitor Tags",
            defaults={
                "description": "Automatically tags common capacitor types based on description.",
                "formula_rules": [
                    {
                        "source_column": "Description",
                        "search_text": "ceramic",
                        "tag_value": "Ceramic Capacitor",
                        "case_sensitive": False
                    },
                    {
                        "source_column": "Description",
                        "search_text": "electrolytic",
                        "tag_value": "Electrolytic Capacitor",
                        "case_sensitive": False
                    }
                ]
            }
        )
        print("   ...OK")
    except Exception as e:
        print(f"   ...FAILED: {e}")
    
    print("[Data Migration] Finished.")


def remove_default_templates(apps, schema_editor):
    """
    Removes the default templates.
    """
    MappingTemplate = apps.get_model('excel_mapper', 'MappingTemplate')
    TagTemplate = apps.get_model('excel_mapper', 'TagTemplate')
    db_alias = schema_editor.connection.alias

    MappingTemplate.objects.using(db_alias).filter(name="General Purpose BOM Template").delete()
    TagTemplate.objects.using(db_alias).filter(name="Capacitor Tags").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0005_mappingtemplate_default_values'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
