# Generated by Django 4.2.20 on 2025-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0006_add_default_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='customer_id_pairs_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mappingtemplate',
            name='spec_pairs_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mappingtemplate',
            name='tags_count',
            field=models.IntegerField(default=1),
        ),
    ]
