# Generated by Django 5.2.6 on 2025-09-22 11:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0007_add_column_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('original_pdf_path', models.CharField(max_length=500)),
                ('total_pages', models.IntegerField()),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('source_type', models.CharField(default='pdf', max_length=10)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_pdf_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_numbers', models.JSONField()),
                ('extracted_headers', models.JSONField()),
                ('extracted_data', models.JSONField()),
                ('confidence_scores', models.JSONField()),
                ('quality_metrics', models.JSONField(default=dict)),
                ('table_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('azure_operation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='excel_mapper.pdfsession')),
            ],
            options={
                'db_table': 'excel_mapper_pdf_extraction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='excel_mapper.pdfsession')),
            ],
            options={
                'db_table': 'excel_mapper_pdf_page',
                'ordering': ['page_number'],
                'unique_together': {('pdf_session', 'page_number')},
            },
        ),
    ]
