# Generated by Django 4.2.7 on 2025-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0008_pdfsession_pdfextractionresult_pdfpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpnOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('scope', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('site', models.CharField(default='IN', max_length=8)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_mpn_oauth_token',
                'ordering': ['-updated_at'],
            },
        ),
    ]

