# Generated by Django 5.2.6 on 2025-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0009_mpn_oauth_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMpnCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn_normalized', models.CharField(db_index=True, max_length=255)),
                ('manufacturer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(default='IN', max_length=8)),
                ('lang', models.CharField(default='en', max_length=8)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('validation_data', models.JSONField()),
                ('is_valid', models.BooleanField(default=False)),
                ('canonical_mpn', models.CharField(blank=True, max_length=255, null=True)),
                ('dkpn', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('end_of_life', models.BooleanField(default=False)),
                ('discontinued', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'excel_mapper_global_mpn_cache',
                'ordering': ['-last_accessed'],
                'indexes': [models.Index(fields=['mpn_normalized'], name='excel_mappe_mpn_nor_64b157_idx'), models.Index(fields=['is_valid'], name='excel_mappe_is_vali_1a6150_idx'), models.Index(fields=['last_accessed'], name='excel_mappe_last_ac_e2ca57_idx'), models.Index(fields=['created_at'], name='excel_mappe_created_977a86_idx')],
                'unique_together': {('mpn_normalized', 'manufacturer_id', 'site', 'lang', 'currency')},
            },
        ),
    ]
