# Generated by Django 5.2.6 on 2025-09-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0010_globalmpncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmpncache',
            name='all_canonical_mpns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
