# Generated by Django 5.2.6 on 2025-09-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0011_globalmpncache_all_canonical_mpns'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='mpn_validation_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
