# Generated by Django 5.2.6 on 2025-09-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0012_mappingtemplate_mpn_validation_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfextractionresult',
            name='page_numbers',
        ),
        migrations.AddField(
            model_name='pdfsession',
            name='processing_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
