# Generated by Django 5.2.6 on 2025-09-29 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0013_add_processing_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('zone_id', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('header', 'Header'), ('table', 'Table Data'), ('text', 'Text')], default='table', max_length=20)),
                ('coordinates', models.JSONField()),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('continuation_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continuations', to='excel_mapper.pdfzone')),
                ('pdf_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='excel_mapper.pdfsession')),
            ],
            options={
                'db_table': 'excel_mapper_pdf_zone',
                'ordering': ['page_number', 'zone_id'],
                'unique_together': {('pdf_session', 'zone_id')},
            },
        ),
    ]
