# Generated by Django 4.2.7 on 2026-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0015_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_id', models.CharField(db_index=True, default='default', max_length=120)),
                ('provider', models.CharField(choices=[('digikey', 'DigiKey'), ('mouser', 'Mouser'), ('element14', 'Element14')], max_length=30)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('configured', models.BooleanField(default=False)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=500)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_provider_credential',
                'ordering': ['scope_id', 'provider'],
                'indexes': [models.Index(fields=['scope_id', 'provider'], name='excel_mappe_scope_i_cca285_idx'), models.Index(fields=['provider', 'configured'], name='excel_mappe_provide_6e225f_idx')],
                'unique_together': {('scope_id', 'provider')},
            },
        ),
    ]
