# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0016_providercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('artifact_type', models.CharField(db_index=True, max_length=80)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_format', models.CharField(choices=[('xlsx', 'Excel workbook'), ('csv', 'CSV'), ('json', 'JSON')], default='xlsx', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('column_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excel_mapper_intermediate_artifact',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['session_id', '-created_at'], name='excel_mappe_session_06646c_idx'),
                    models.Index(fields=['artifact_type', '-created_at'], name='excel_mappe_artifac_62a765_idx'),
                ],
            },
        ),
    ]
