# Generated by Codex on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0017_intermediateartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomWorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_signature', models.JSONField(blank=True, default=dict)),
                ('workflow', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'excel_mapper_bom_workflow_template',
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['name'], name='excel_mappe_name_18e9ee_idx'),
                    models.Index(fields=['-updated_at'], name='excel_mappe_updated_ea098a_idx'),
                ],
            },
        ),
    ]
