# Generated by Codex on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0018_bomworkflowtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('source_requirements', models.JSONField(blank=True, default=dict)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('provider_snapshot', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usage_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'excel_mapper_processing_template',
                'ordering': ['-updated_at'],
                'indexes': [
                    models.Index(fields=['name'], name='excel_mappe_name_f9fb29_idx'),
                    models.Index(fields=['status', '-updated_at'], name='excel_mappe_status_510984_idx'),
                ],
            },
        ),
    ]
