# Generated by Django 4.2.7 on 2026-08-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0020_mappingtemplate_default_dynamic_counts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bomworkflowtemplate',
            new_name='excel_mappe_name_d14a11_idx',
            old_name='excel_mappe_name_18e9ee_idx',
        ),
        migrations.RenameIndex(
            model_name='bomworkflowtemplate',
            new_name='excel_mappe_updated_ea631f_idx',
            old_name='excel_mappe_updated_ea098a_idx',
        ),
        migrations.RenameIndex(
            model_name='intermediateartifact',
            new_name='excel_mappe_session_a43644_idx',
            old_name='excel_mappe_session_06646c_idx',
        ),
        migrations.RenameIndex(
            model_name='intermediateartifact',
            new_name='excel_mappe_artifac_3644dc_idx',
            old_name='excel_mappe_artifac_62a765_idx',
        ),
        migrations.RenameIndex(
            model_name='processingtemplate',
            new_name='excel_mappe_name_38d5cd_idx',
            old_name='excel_mappe_name_f9fb29_idx',
        ),
        migrations.RenameIndex(
            model_name='processingtemplate',
            new_name='excel_mappe_status_2975d5_idx',
            old_name='excel_mappe_status_510984_idx',
        ),
    ]
