# Generated by Django 4.2.7 on 2026-08-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0022_providermpncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappingtemplate',
            name='bom_structure',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
