# Generated by Django 4.2.7 on 2026-09-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_mapper', '0028_bomstructurepattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryLearningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure_signature', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('raw_mpn', models.TextField(blank=True, default='')),
                ('raw_manufacturer', models.TextField(blank=True, default='')),
                ('normalized_mpn', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('normalized_manufacturer', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('promoted', 'Promoted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'excel_mapper_directory_learning_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('normalized_alias', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(default='seed', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_manufacturer_alias',
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ManufacturerDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255, unique=True)),
                ('source', models.CharField(default='seed', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_manufacturer_directory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MpnDirectoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpn', models.CharField(max_length=255)),
                ('normalized_mpn', models.CharField(max_length=255, unique=True)),
                ('exact_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('grouped_pattern', models.CharField(blank=True, default='', max_length=255)),
                ('character_classes', models.CharField(blank=True, default='', max_length=255)),
                ('mpn_length', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(default='seed', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_mpn_directory',
                'ordering': ['mpn'],
            },
        ),
        migrations.CreateModel(
            name='MpnManufacturerPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='seed', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('confirmation_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_mpn_manufacturer_pair',
                'ordering': ['mpn__mpn', 'manufacturer__name'],
            },
        ),
        migrations.CreateModel(
            name='MpnPatternEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(max_length=32)),
                ('signature', models.CharField(max_length=255)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='seed', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'excel_mapper_mpn_pattern_entry',
                'ordering': ['pattern_type', 'signature'],
            },
        ),
        migrations.AddIndex(
            model_name='mpnpatternentry',
            index=models.Index(fields=['pattern_type', 'signature'], name='excel_mappe_pattern_6a342f_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpnpatternentry',
            constraint=models.UniqueConstraint(fields=('pattern_type', 'signature'), name='unique_mpn_pattern_signature'),
        ),
        migrations.AddField(
            model_name='mpnmanufacturerpair',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpn_pairs', to='excel_mapper.manufacturerdirectoryentry'),
        ),
        migrations.AddField(
            model_name='mpnmanufacturerpair',
            name='mpn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_pairs', to='excel_mapper.mpndirectoryentry'),
        ),
        migrations.AddIndex(
            model_name='mpndirectoryentry',
            index=models.Index(fields=['status', 'normalized_mpn'], name='excel_mappe_status_e8ef4c_idx'),
        ),
        migrations.AddIndex(
            model_name='mpndirectoryentry',
            index=models.Index(fields=['grouped_pattern'], name='excel_mappe_grouped_45b7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='mpndirectoryentry',
            index=models.Index(fields=['exact_pattern'], name='excel_mappe_exact_p_f4705f_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturerdirectoryentry',
            index=models.Index(fields=['status', 'normalized_name'], name='excel_mappe_status_b43e18_idx'),
        ),
        migrations.AddIndex(
            model_name='manufacturerdirectoryentry',
            index=models.Index(fields=['name'], name='excel_mappe_name_291d2b_idx'),
        ),
        migrations.AddField(
            model_name='manufactureralias',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='excel_mapper.manufacturerdirectoryentry'),
        ),
        migrations.AddField(
            model_name='directorylearningevent',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directory_learning_events', to='excel_mapper.bomstructurepattern'),
        ),
        migrations.AddIndex(
            model_name='mpnmanufacturerpair',
            index=models.Index(fields=['status', 'mpn', 'manufacturer'], name='excel_mappe_status_f565be_idx'),
        ),
        migrations.AddConstraint(
            model_name='mpnmanufacturerpair',
            constraint=models.UniqueConstraint(fields=('mpn', 'manufacturer'), name='unique_mpn_manufacturer_pair'),
        ),
        migrations.AddIndex(
            model_name='manufactureralias',
            index=models.Index(fields=['is_active', 'normalized_alias'], name='excel_mappe_is_acti_2db05b_idx'),
        ),
        migrations.AddIndex(
            model_name='directorylearningevent',
            index=models.Index(fields=['status', '-created_at'], name='excel_mappe_status_624836_idx'),
        ),
    ]
